#!/bin/sh

# Set these paths appropriately

BIN="/home/etudiant/Téléchargements/Treetagger/bin"
CMD="/home/etudiant/Téléchargements/Treetagger/cmd"
LIB="/home/etudiant/Téléchargements/Treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
